version: "3" 
services:
    redis-server:
        image: "redis"
        volumes: 
          - ./data:/data 
        command: ["redis-server", "--save", "1 1"]
    node-app:
        image: "renuka/visits"
        build: ./
        ports:
            - "8081:8081"